### ISSUE TITLE
Doesn't work for Pokémon with spaces in their names

### ISSUE THREAD

**Issue by evandixon** [projectpokemon/Smeargle#1]
E.g. `Mr. Mime`

**Comment by sand-head** [comment]
might be fixable by modifying line 117 of Program.cs, String.Split accepts a second integer argument that supplies a max number of substrings: https://docs.microsoft.com/en-us/dotnet/api/system.string.split?view=netcore-2.2#System_String_Split_System_Char___System_Int32_
